### ISSUE TITLE
Work without Kohana

### ISSUE THREAD

**Issue by tucuta** [coreyworrell/Menu#1]
Hi, the code looks great but I have a question.
As I run this class without Kohana because i see that it calls some classes that do not exist, for example HTML::anchor and HTML::attributes

**Comment by coreyworrell** [comment]
Hi @tucuta,

Yes there are a few method calls in the code source that you would need to swap out: `HTML::attributes`, `HTML::anchor`, and `Kohana::debug`. Then you could use it without Kohana. You can refer to Kohana source code to perhaps copy the code from those methods into the menu class itself.
